apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvct
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  volumeName: my-pvt