apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-nov
      image: httpd
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /mnt
          name: new-vol
  volumes:
    - name: new-vol
      persistentVolumeClaim:
        claimName: my-pvct
      