apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: my-sts
  labels:
    app: mysql
spec:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrett
                  key: DATABASE_PASS
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrett
                  key: DATABASE_USER

  replicas: 3
  selector:
    matchLabels:
      app: mysql
